sudo: required
services:
  - docker
language: node_js
node_js:
  - "8"
script:
  - npm install
  - npm run build
  - npm run coveralls
cache:
  directories:
    - "node_modules"
after_success:
  - if [[ "$TRAVIS_TAG" == *"-"* ]]; then export docker_tag=latest-unstable; else export docker_tag=latest; fi;
  - test "$TRAVIS_TAG" != "" && version=${TRAVIS_TAG:1}; 
  - test "$TRAVIS_TAG" != "" && docker build -t gyselroth/kube-icinga:$version .
  - test "$TRAVIS_TAG" != "" && docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - test "$TRAVIS_TAG" != "" && docker tag gyselroth/kube-icinga:$version gyselroth/kube-ldap:$docker_tag
  - test "$TRAVIS_TAG" != "" && docker push gyselroth/kube-icinga:$version
  - test "$TRAVIS_TAG" != "" && docker push gyselroth/kube-icinga:$docker_tag
