apiVersion: v1
kind: Secret
metadata:
  name: icinga-credentials
  namespace: kube-system
type: Opaque
data:
  username: a3ViZS1pY2luZ2E=
  password: a3ViZS1pY2luZ2E=
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-icinga
subjects:
- kind: ServiceAccount
  name: kube-icinga
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-icinga
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-icinga
  labels:
    k8s-app: kube-icinga
rules:
- apiGroups:
  - ""
  - extensions
  resources:
  - namespaces
  - ingresses
  - services
  - nodes
  - persistentvolumes
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - extensions
  - ""
  resources:
  - ingresses
  - ingresses/status
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-icinga
  namespace: kube-system
  labels:
    k8s-app: kube-icinga
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: kube-icinga
  name: kube-icinga
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kube-icinga
  template:
    metadata:
      labels:
        k8s-app: kube-icinga
    spec:
      containers:
      - image: gyselroth/kube-icinga:latest
        imagePullPolicy: Always
        name: kube-icinga
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: ICINGA_ADDRESS
          value: icinga_address
        - name: ICINGA_API_USER
          valueFrom:
            secretKeyRef:
              name: icinga-credentials
              key: username
        - name: ICINGA_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: icinga-credentials
              key: password
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-icinga
      serviceAccountName: kube-icinga
      terminationGracePeriodSeconds: 30
